---
- name: Install davfs2
  ansible.builtin.package:
    name: davfs2
    state: present

- name: Configure secrets
  ansible.builtin.lineinfile:
    path: /etc/davfs2/secrets
    regexp: "^{{ nextcloud_davfs.url }}"
    line: "{{ nextcloud_davfs.url }} {{ nextcloud_davfs.clouduser }} {{ nextcloud_davfs.password }}"

- name: Configure dav2fs option buf_size
  ansible.builtin.lineinfile:
    path: /etc/davfs2/davfs2.conf
    regexp: "buf_size"
    line: "buf_size        32"

- name: Configure dav2fs option use_locks
  ansible.builtin.lineinfile:
    path: /etc/davfs2/davfs2.conf
    regexp: "use_locks"
    line: "use_locks        0"

- name: Configure dav2fs option cache_size
  ansible.builtin.lineinfile:
    path: /etc/davfs2/davfs2.conf
    regexp: "cache_size"
    line: "cache_size        500"

- name: Configure dav2fs option table_size
  ansible.builtin.lineinfile:
    path: /etc/davfs2/davfs2.conf
    regexp: "table_size"
    line: "table_size        32768"

- name: "Ensure Nextcloud directory in /home/{{ nextcloud_davfs.osuser }}"
  ansible.builtin.file:
    path: "/home/{{ nextcloud_davfs.osuser }}/Nextcloud"
    state: directory
    owner: "{{ nextcloud_davfs.osuser }}"
    group: root
    mode: "0700"

- name: "Configure Nextcloud mount in /home/{{ nextcloud_davfs.osuser }}"
  ansible.posix.mount:
    path: "/home/{{ nextcloud_davfs.osuser }}/Nextcloud"
    src: https://cloud.oxi.ch/remote.php/webdav
    fstype: davfs
    opts: "user,auto,uid={{ nextcloud_davfs.osuser }},file_mode=600,dir_mode=700,_netdev"
    state: mounted

- name: "Ensure Nextcloud .nextrsync directory in /home/{{ nextcloud_davfs.osuser }}"
  ansible.builtin.file:
    path: "/home/{{ nextcloud_davfs.osuser }}/.nextrsync"
    state: directory
    owner: "{{ nextcloud_davfs.osuser }}"
    group: root
    mode: "0700"
  when: nextcloud_davfs.nextrsync

- name: "Configure .nextrsync mount in /home/{{ nextcloud_davfs.osuser }}"
  ansible.posix.mount:
    path: "/home/{{ nextcloud_davfs.osuser }}/.nextrsync"
    src: tmpfs
    fstype: tmpfs
    opts: "size=50m,nosuid,mode=0700,gid=root,uid={{ nextcloud_davfs.osuser }}"
    state: mounted
  when: nextcloud_davfs.nextrsync

- name: Configure nextcloud cleanup
  ansible.builtin.cron:
    name: "Nextcloud tmp cleanup for {{ nextcloud_davfs.osuser }}"
    user: "{{ nextcloud_davfs.osuser }}"
    hour: 4
    minute: 30
    day: 5
    job: "/bin/bash /home/{{ nextcloud_davfs.osuser }}/.nextrsync/scripts/cleanup"
  when: nextcloud_davfs.cleanup

- name: Configure nextrsync crontab
  ansible.builtin.cron:
    name: "Nextrsync for {{ nextcloud_davfs.osuser }}"
    user: "{{ nextcloud_davfs.osuser }}"
    minute: "*/5"
    job: "/bin/bash /home/{{ nextcloud_davfs.osuser }}/Nextcloud/scripts/nextrsync"
  when: nextcloud_davfs.nextrsync

- name: Configure nextrsync at boot
  ansible.builtin.cron:
    name: "Nextrsync for {{ nextcloud_davfs.osuser }} at boot"
    user: "{{ nextcloud_davfs.osuser }}"
    special_time: reboot
    job: "/bin/bash /home/{{ nextcloud_davfs.osuser }}/Nextcloud/scripts/nextrsync"
  when: nextcloud_davfs.nextrsync
